-- AlterTable
ALTER TABLE "Workout" ADD COLUMN     "MODEL1" DOUBLE PRECISION,
ADD COLUMN     "MODEL2" DOUBLE PRECISION,
ADD COLUMN     "MODEL3" DOUBLE PRECISION,
ADD COLUMN     "MODEL4" DOUBLE PRECISION;
